use_frameworks!

platform :ios, '8.0'

target 'podTestLibraray_Example' do
  pod 'podTestLibraray', :path => '../'

  target 'podTestLibraray_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
